### ISSUE TITLE
New feature wanted: open reference pdf

### ISSUE THREAD

**Issue by MiuKaShi** [ferdinandyb/bibtexcite.vim#1]
Thank you for creating very useful citation plugin.
It works very well in my VIM, but the current version can not open the cited reference from vim.
Do you have any idea to realize this function.
Thank you

**Comment by ferdinandyb** [comment]
It should be possible to try and open whatever is in the file keyword with the system default. Or maybe easier from a maintenance perspective: have a user setting which tells what command to call, so I don't have to worry about the different OS-s or user preferences.

**Comment by ferdinandyb** [comment]
I implemented this in the latest commit, can you check if it work for you?

**Comment by MiuKaShi** [comment]
Thanks for adding this feature, I tested it and it works well in most cases.
Only fails when there is more than one pdf exists, e.g.
file ={1.pdf;2.pdf}
Maybe for multi-file cases, l:filepath needs to be filtered more carefully.
Thank you again for considering my request

**Comment by Pieter1024** [comment]
I ran into the same issue as @MiuKaShi when there are several linked files.

An easy fix would be to just open the first attachment and ignore the rest. I've gotten that to work by adding the following after https://github.com/ferdinandyb/bibtexcite.vim/blob/master/autoload/bibtexcite.vim#L152

`let l:filepath = substitute(l:filepath, ';.*$', '', 'g')`

That basically removes everything in the file path after ';'

A neater solution would be to have the user choose which attachment they want to open.

**Comment by ferdinandyb** [comment]
I thought there was an easy way around this, by passing all of the files as arguments to the command, as most programs seem to handle it (I checked zathura and evince on my machine), but `xdg-open` itself actually dies with an error on that and sioyek just opens the first argument.

I could imagine an extra option that allows the user to specify to a) pass all, b) pass first c) open a dialog if there are more files, and then the user could configure it based on their command and preferences. What do you think?

**Comment by MiuKaShi** [comment]
> I thought there was an easy way around this, by passing all of the files as arguments to the command, as most programs seem to handle it (I checked zathura and evince on my machine), but `xdg-open` itself actually dies with an error on that and sioyek just opens the first argument.
> 
> I could imagine an extra option that allows the user to specify to a) pass all, b) pass first c) open a dialog if there are more files, and then the user could configure it based on their command and preferences. What do you think?

Yes, I think so. It's better to have a popup window for users to select the file

Currently, I am using dmenu for that by add 

```
 let l:filepath = substitute(l:filepath[1], ';', '\\n', 'g')
 let l:filepath = system('echo ' . shellescape(l:filepath) . ' | dmenu -p "Select file: "')
```

It's an ugly way, and maybe better to use nvim to select the file

**Comment by ferdinandyb** [comment]
Ok. I'll implement the option with a) and b) quickly, and then look into how to solve the selection within `vim` to reduce dependency on yet another tool.

**Comment by ferdinandyb** [comment]
It's done, except for allowing to choose from multiple files (so now you either open the first one or all of them). I'll look into implementing a dialog for choosing sometime later.

**Comment by ferdinandyb** [comment]
Maybe `fzf` could be used for this.
