### ISSUE TITLE
Bug: bibfile path that contains spaces doesn't work

### ISSUE THREAD

**Issue by Pieter1024** [ferdinandyb/bibtexcite.vim#2]
The path to my bibtex file contains spaces. When I run BibtexciteShowcite, the pop-up shows two bibtool errors: it can't open the first part of the path as a bib file, and it can't open the second part of the path as a bib file.

I can simply fix this by adding quotes to the bibtool calling string in autoload/bibtexcite.vim:117. That makes everything work as expected. However, I'm pretty sure that would break support for multiple bib files.

**Comment by Pieter1024** [comment]
I'm setting the bibtex file path through g:bibtexcite_bibfile

**Comment by ferdinandyb** [comment]
Thanks for the report, I'll take a look at it soon!

**Comment by ferdinandyb** [comment]
Can you check if the latest commit fixes the issue?

**Comment by Pieter1024** [comment]
It does, thanks for fixing this!

**Comment by ferdinandyb** [comment]
I also added an "open pdf" option (see the other issue and the help), I'd be happy if you could also check if that works for you! Thanks
