### ISSUE TITLE
Install on LazyVim

### ISSUE THREAD

**Issue by weberam2** [ferdinandyb/bibtexcite.vim#6]
Hello,

I am trying to get this installed with LazyVim but so far no luck

I have this bibexcite.lua file in my plugins folder:

```
return {
  {
    "ferdinand/bibexcite.vim",
  },
}
```

But when lazy loads, it can't install it...

Any advice?

**Comment by ferdinandyb** [comment]
Hey,

2024. márc. 30. 19:04:39 Alexander Weber ***@***.***>:

> Hello,
>
> I am trying to get this installed with LazyVim but so far no luck
>
> I have this bibexcite.lua file in my plugins folder:
>
> ```
> return {
>   {
>     "ferdinand/bibexcite.vim",

this is misspellt, it should be ferdinandY, with a y at the end, and 
bibTexcite.vim with a t.


Your lua file is also missing a t from bibtex, but I don't know if that 
matters or not, probably not.

**Comment by weberam2** [comment]
I feel like an idiot.

Thank you for helping me. It has installed!

**Comment by weberam2** [comment]
Ok, now I'm not sure how to make the configuration with LazyVim specifically...

**Comment by weberam2** [comment]
I'm getting somewhere, but not able to open a file yet using `BibtexciteOpenfile`

```
return {
  {
    "ferdinandyb/bibtexcite.vim",
    config = function()
      vim.g.bibtexcite_bibfile = "~/Dropbox/AssistantProf_BCCHRI/MyFullZoteroLibrary.bib"
      vim.g.bibtexcite_openfilecommand = "evince"
      vim.g.bibtexcite_openfilesetting = 3
    end,
  },
}
```

**Comment by ferdinandyb** [comment]
What error are you getting when trying to open a file?

**Comment by ferdinandyb** [comment]
Do you have fzf installed? I realized it is implied, but not mentioned in the docs. I updated the Installation part.

**Comment by weberam2** [comment]
Ah, I had fzf installed on my shell, but only `telescope-fzf-native.nvim` on my nvim

I now have them installed:
![image](https://github.com/ferdinandyb/bibtexcite.vim/assets/16805029/2351d2bd-3b53-47cd-82ec-f249539bdb72)

But I'm still getting this error:

![image](https://github.com/ferdinandyb/bibtexcite.vim/assets/16805029/f09dbfc1-ab49-44d4-ad8a-4e2a5f8f71ea)
But the bib file says that that entry does have a file:

> @article{duboisEarlyDevelopmentBrain2014,
  title = {The Early Development of Brain White Matter: {{A}} Review of Imaging Studies in Fetuses, Newborns and Infants},
  shorttitle = {The Early Development of Brain White Matter},
  author = {Dubois, J. and {Dehaene-Lambertz}, G. and Kulikova, S. and Poupon, C. and H{\"u}ppi, P.S. and {Hertz-Pannier}, L.},
  year = {2014},
  month = sep,
  journal = {Neuroscience},
  volume = {276},
  pages = {48--71},
  issn = {03064522},
  doi = {10.1016/j.neuroscience.2013.12.044},
  urldate = {2022-08-16},
  langid = {english},
  file = {/home/weberam2/Zotero/storage/U5E8TXAU/Dubois et al. - 2014 - The early development of brain white matter A rev.pdf}
}

**Comment by weberam2** [comment]
I CAN confirm that at least BibtexciteInsert is working!
But nothing else...

**Comment by weberam2** [comment]
Here are some more errors notifications

![image](https://github.com/ferdinandyb/bibtexcite.vim/assets/16805029/9f6f0087-381d-42b9-9dce-d3bb1369db26)

**Comment by ferdinandyb** [comment]
I'm sorry there are issues, I will need to double check this first. I have personally never used LazyVim, although it doesn't seem like something related to that. Let me get back to you a bit later.

**Comment by ferdinandyb** [comment]
Could you be more specific in what exactly you are doing to trigger that error? Just calling `:BibtexciteOpenfile` with the cursor on the citation key of the entry you copy-pasted above?

**Comment by ferdinandyb** [comment]
Ok, so after a bit of an investigation I think I found an issue running the plugin under nvim, regarding either long filenames, or filenames with spaces in them. Could you try to open a file where the entire filepath does not contain spaces? In the meanwhile I'll work on fixing the issue.

**Comment by ferdinandyb** [comment]
Ok, so there are two unrelated issues regarding `nvim`, one of them is easier so I should be able to fix that in a day or two. The other is a bit more tricky, that may need more time. Please bear with me, I'd be happy for an `nvim` tester :)

**Comment by weberam2** [comment]
> I'm sorry there are issues, I will need to double check this first. I have personally never used LazyVim, although it doesn't seem like something related to that. Let me get back to you a bit later.

omg no need to apologize!

**Comment by weberam2** [comment]
> Ok, so after a bit of an investigation I think I found an issue running the plugin under nvim, regarding either long filenames, or filenames with spaces in them. Could you try to open a file where the entire filepath does not contain spaces? In the meanwhile I'll work on fixing the issue.

I tried to open a file with no spaces, but still no luck

Same error as before

The file is: `/home/weberam2/Zotero/storage/H7Y95EP9/Campbell_et_al_2021_Fractal-Based_Analysis_of_fMRI_BOLD_Signal_During_Naturalistic_Viewing.pdf`

Maybe the name is too long?

**Comment by weberam2** [comment]
> Could you be more specific in what exactly you are doing to trigger that error? Just calling `:BibtexciteOpenfile` with the cursor on the citation key of the entry you copy-pasted above?

Yes, my cursor is over the citation
![image](https://github.com/ferdinandyb/bibtexcite.vim/assets/16805029/bb9a9bd2-3b6d-4de0-8991-39c194b61f88)

and then I call `:BibtexciteOpenfile`

**Comment by weberam2** [comment]
wait!! It works 
If the entry has @ at the beginning, and is not surrounded by {} it works

![image](https://github.com/ferdinandyb/bibtexcite.vim/assets/16805029/9547c482-3141-4cc4-bcf0-8e12da811878)

The top one doesn't work
the bottom does

and I can confirm when there is a space, it doesn't open:
![image](https://github.com/ferdinandyb/bibtexcite.vim/assets/16805029/19f15e11-2c61-48aa-85ac-f1129370c55e)

**Comment by weberam2** [comment]
The problem is, \bibentry{} doesn't compile when I have @ in front:
`\bibentry{campbellFractalBasedAnalysisFMRI2021}` works for latex compiling
`\bibentry{campbellFractalBasedAnalysisFMRI2021}` doesn't

**Comment by ferdinandyb** [comment]
Just for clarification, you are using latex, right? I'll add filetype detection and a bit more documentation on this ... Also, what exactly is the string your cursor is on? Markdown/pandoc looks for `@citekey`, latex looks for `\cite{citekey}`.

**Comment by ferdinandyb** [comment]
@weberam2 I pushed a fix for one of the issues you saw. I'm hoping most of the commands will work now, though I noticed the autocomplete is not quite ok yet. For latex, I'm wondering if beside `\cite` what other commands should be treated as possible citations. I guess `\bibentry` should definitely be on the list. For now you can test stuff, by say, calling `:BiblatexShowcite latex` on a `\cite{key}`. I'll push filetype detection and `\bibentry` likely sometime tomorrow.

**Comment by ferdinandyb** [comment]
I think I managed to fix all the issues and add filetype detection as well, so the commands should now just work without havnig to add "latex" to them in tex files (nb. it uses vim :set filetype, so will only work if the filetype is correctly set to `tex`).

**Comment by weberam2** [comment]
> Just for clarification, you are using latex, right? I'll add filetype detection and a bit more documentation on this ... Also, what exactly is the string your cursor is on? Markdown/pandoc looks for `@citekey`, latex looks for `\cite{citekey}`.

Yes, I've been using Latex. Sorry, I should have specified

>For latex, I'm wondering if beside \cite what other commands should be treated as possible citations. I guess \bibentry should definitely be on the list

I'm not sure. \citep is another one...

I haven't had a lot of time to check, but so far everything seems to be working! Great job! And great plugin :)

I'll let you know if I have more troubles
