### ISSUE TITLE
Error when running BibtexciteInsert

### ISSUE THREAD

**Issue by LucasPa** [ferdinandyb/bibtexcite.vim#7]
Hello,

I'm very excited about using bibtextcite but after installing it, I can the following error when trying to run `BibtexciteInsert` (sorry I did not find any way to copy the message)

![image](https://github.com/ferdinandyb/bibtexcite.vim/assets/6225092/03fa960b-42bf-4521-89b0-a2a2d7812706)
![image](https://github.com/ferdinandyb/bibtexcite.vim/assets/6225092/14b645a8-db08-4f62-99b0-728fcff62109)
![image](https://github.com/ferdinandyb/bibtexcite.vim/assets/6225092/a2ee4ea2-805f-46cd-b37f-abdd7e3add3c)

Information that might be relevant:

- Are you using vim or neovim? vim
- What is the output of `:set filetype?` filetype=bib
- Did you change any of the default configurations? no
- Did you install all the prerequisites? yes

**Comment by ferdinandyb** [comment]
@LucasPa Thanks for reporting this! I can't reproduce it, so I'm assuming it's a vim version error. What version of vim are you running? I'll try to run it with whatever version you have and see if I can reproduce. Also, is the command you are trying to run just plain `BibtexciteInsert` while you are in a `.bib` file?

On the other hand: what is the use-case you have for running insert in a .bib file? The idea would be that you have a .bib file with citation entries and you want to insert into some other file (latex, markdown or some other text).

**Comment by LucasPa** [comment]
Thanks for your answer.
I use the version 8.0.1763 of vim. I try to run plain `BibtextciteInsert` in a `.bib` file. The aim is to insert files in this `.bib` file citations from my Zotero database. Is it not the aim of the command `BibtextciteInsert`?

**Comment by ferdinandyb** [comment]
> Thanks for your answer. I use the version 8.0.1763 of vim. 

Hmm, that version is more than 6 years old, can you try with a newer version? I'll look into whether I can repro your error on this version. 

> I try to run plain `BibtextciteInsert` in a `.bib` file. The aim is to insert files in this `.bib` file citations from my Zotero database. Is it not the aim of the command `BibtextciteInsert`?

No, it's not. It's for inserting citations into say a LaTeX file _from_ a `.bib`. For creating a `.bib` database from Zotero I think Zotero itself offers better solutions, see the README:
> The plugin is being developed to work well with [Zotero](https://www.zotero.org/) as the citation manager, using the [Better Biblatex](https://retorque.re/zotero-better-bibtex/) plugin to synchronize a monolithic .bib file, but it should work with other workflows as well (also see tips below).

And also here: https://github.com/ferdinandyb/bibtexcite.vim?tab=readme-ov-file#tips

Do you have a use case that is not covered by these solutions?

**Comment by ferdinandyb** [comment]
So I did a test, and it seems that we need at least vim 8.2 because of the pop-up for fetching citation info anyway, so I'm not going to fix this. Please update to at least vim version 8.2 (released 4 and a half years ago), but you would probably have a better experience with an even later version of 8.X.
