### ISSUE TITLE
Support for quarto / .qmd files

### ISSUE THREAD

**Issue by weberam2** [ferdinandyb/bibtexcite.vim#8]
**Describe the bug**
I can't seem to get this to work with a .qmd file
When I insert a citation, it is not in @bibtex format (e.g. @alsopRecommendedImplementationArterial2015)
I also can't seem to open the pdf...

Information that might be relevant:

- What version of vim or neovim are you using?
NVIM v0.10.0-dev-3097+g064f3e42e
Build type: RelWithDebInfo
LuaJIT 2.1.1713484068

- What is the output of `:set filetype?`
quarto

- What is your `bibtexcite.vim` configuration?
I'm using lazyvim:
```
return {
  {
    "junegunn/fzf",
  },
  {
    "junegunn/fzf.vim",
  },
  {
    "ferdinandyb/bibtexcite.vim",
    config = function()
      vim.g.bibtexcite_bibfile = "~/Dropbox/AssistantProf_BCCHRI/MyFullZoteroLibrary.bib"
      vim.g.bibtexcite_openfilecommand = "evince"
      vim.g.bibtexcite_openfilesetting = 3
    end,
  },
}
```

- What is the exact command you are trying to run?

BibtexciteOpenfile

- Did you install all the prerequisites?

Yes

- If trying to access a `.bib` entry:
    - copy the entire line your cursor is on into the report, and indicate where your cursor is at

@alsopRecommendedImplementationArterial2015

    - copy the relevant entry from your `.bib` file

@article{alsopRecommendedImplementationArterial2015,
  title = {Recommended Implementation of Arterial Spin-Labeled Perfusion {{MRI}} for Clinical Applications: {{A}} Consensus of the {{ISMRM}} Perfusion Study Group and the {{European}} Consortium for {{ASL}} in Dementia: {{Recommended Implementation}} of {{ASL}} for {{Clinical Applications}}},
  shorttitle = {Recommended Implementation of Arterial Spin-Labeled Perfusion {{MRI}} for Clinical Applications},
  author = {Alsop, David C. and Detre, John A. and Golay, Xavier and G{\"u}nther, Matthias and Hendrikse, Jeroen and {Hernandez-Garcia}, Luis and Lu, Hanzhang and MacIntosh, Bradley J. and Parkes, Laura M. and Smits, Marion and {van Osch}, Matthias J. P. and Wang, Danny J. J. and Wong, Eric C. and Zaharchuk, Greg},
  year = {2015},
  month = jan,
  journal = {Magnetic Resonance in Medicine},
  volume = {73},
  number = {1},
  pages = {102--116},
  issn = {07403194},
  doi = {10.1002/mrm.25197},
  urldate = {2022-04-18},
  langid = {english},
  keywords = {arterial spin labeling,Blood Flow Velocity,Brain,cerebral blood flow,Cerebrovascular Circulation,Dementia,European Union,Humans,Magnetic Resonance Angiography,Neurology,perfusion,Practice Guidelines as Topic,Spin Labels},
  file = {/home/weberam2/Dropbox/AssistantProf_BCCHRI/Zotero_Obsidian/Zotero/Alsop_et_al_2015_Recommended_implementation_of_arterial_spin-labeled_perfusion_MRI_for_clinical.pdf;/home/weberam2/Dropbox/AssistantProf_BCCHRI/Zotero_Obsidian/Zotero/Alsop_et_al_2015_Recommended_implementation_of_arterial_spin-labeled_perfusion_MRI_for_clinical2.pdf}
}

**Comment by ferdinandyb** [comment]
Sorry for the late reply. [This](https://github.com/ferdinandyb/bibtexcite.vim/blob/master/autoload/bibtexcite.vim#L91) is how we currently decide what is the default output. Since your filetype is quarto that will default to markdown output, instead of pandoc. There's two ways you can go here:

- force the outputtype `:BibtexciteInsert pandoc` see [docs](https://github.com/ferdinandyb/bibtexcite.vim/blob/master/doc/bibtexcite.txt#L74)
- it's possible to set up a certain filetype to also act as markdown, that is how pandoc works, although I haven't tried that with the plugin

A third option would be to convince me that the plugin should ship with default of pandoc for quarto files, but I don't know anything about what this is and I would not want to add something that might break other user's expectations, so I would need a little more information on this.

**Comment by ferdinandyb** [comment]
We're talking about [this](https://quarto.org/docs/get-started/hello/neovim.html) right? I've briefly used Rmarkdown before. Does qmd handle pandoc type citation by default?  Because then it would make sense to have that as a default.

**Comment by weberam2** [comment]
Hello!

Yes, we are talking about Quarto (the link you shared). It is for open-source scientific publishing. It's essentially RMarkdown, but better, as it can also handle python, julia, and has a bunch of other features. It's by the same people who made RStudio:

> In 2022, Posit announced an R Markdown-like publishing system called Quarto. In addition to combining results of R, code and results using Python, Julia, Observable JavaScript, and Jupyter notebooks can also be used in Quarto documents. Compared to the file extension .Rmd that R Markdown has, Quarto documents have the file extension .qmd.

[References](https://quarto.org/docs/authoring/citations.html) are by default @citation or [@citation], which I believe is the same as [pandoc](https://pandoc.org/chunkedhtml-demo/8.20-citation-syntax.html)

I'm pretty sure qmd files are converted using pandoc under the hood: 
![image](https://github.com/user-attachments/assets/fcdadf12-9271-4dd5-9b30-0f2693093e84)

**Comment by ferdinandyb** [comment]
Please reopen the issue if it does not solve it!
